fixtures:
  repositories:
    validate_multi:
      repo: "git://github.com/trlinkin/puppet-validate_multi"
      ref: "0.1.0"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.3.2"
  symlinks:
    nsswitch: "#{source_dir}"
