language: ruby
script:
  - "bundle exec rake syntax"
  - "bundle exec rake lint"
  - "bundle exec rake metadata_lint"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
 - 2.1.0
env:
 - PUPPET_GEM_VERSION="4.0.0"
 - PUPPET_GEM_VERSION="4.10.1"
 - PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
