language: ruby
script:
  - "bundle exec rake syntax"
  - "bundle exec rake lint"
  - "bundle exec rake metadata_lint"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.0
 - 2.2.0
 - ruby-head
env:
 - PUPPET_GEM_VERSION="~> 4.0.0"
 - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  allow_failures:
    - rvm: 2.2.0
    - rvm: ruby-head
notifications:
  email: false
