language: ruby
script:
  - "bundle exec rake syntax"
  - "bundle exec rake lint"
  - "bundle exec rake metadata"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
 - 1.9.3-p484
 - 2.0.0
 - ruby-head
env:
 - PUPPET_GEM_VERSION="< 4.0.0"
 - PUPPET_GEM_VERSION="> 4.0.0"
matrix:
  exclude:
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="< 4.0.0"
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
